### PR TITLE
chrf: assert if refs are not in a list (#121)

### PR DESCRIPTION
**Pull request by ozancaglayan**
Bail out if references are not given in a list, for `chrf.sentence_score()` method.

### CODE REVIEW

**Review by martinpopel — APPROVED** [review]
Thanks.

**Comment by bricksdont** [comment]
Bumping this issue; the build for Python 3.5 fails, I think because mecab-python3 is not compatible with Python 3.5

Other than that, I think that this PR is straightforward and could be merged - thanks!

**Comment by ozancaglayan** [comment]
yeah I noticed that one as well.

**Comment by ozancaglayan** [comment]
@polm can we pin to mecab 1.0.2 here, so that we're still supporting python 3.5 (until we decide whether we drop support for 3.5 for sacreBLEU as well) ?

**Comment by ozancaglayan** [comment]
Thanks @polm , pinning to 1.0.3 seemed to fix it

**Pull request merged**
