### PR TITLE
switched from travis to github action

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
Please (squash) merge and then fold into `v2`. I hope this resolves the problems with Travis and merging. I am on vacation this week.

**Review by ozancaglayan — APPROVED** [review]

**Comment by ozancaglayan** [comment]
So I should first merge this to `master` right?

**Comment by mjpost** [comment]
I think if you merge this into v2 now it should fix the earlier issue?

**Comment by ozancaglayan** [comment]
Yes, I'll take a look at this tomorrow. I also need to integrate the Windows and Mac OS tests that I've added to travis in this branch, go Github actions. Many thanks for the switch, happy vacations!

**Pull request merged**
