### PR TITLE
Version bump to 2.3.3

### PR DESCRIPTION
**Pull request by dustalov**
Let's roll it out.

### CODE REVIEW

**Comment by dustalov** [comment]
@martinpopel

**Comment by martinpopel** [comment]
I would prefer @mjpost to release it to PyPI (as he always did). I'm not sure if I have the rights to do so.

**Comment by mjpost** [comment]
I can do this later today

**Review by mjpost — APPROVED** [review]

**Comment by mjpost** [comment]
Done, tagged, and release pushed to pypi.

**Pull request merged**
