### PR TITLE
reorganization: datasets and tokenizers are moved to separate .py modules

### PR DESCRIPTION
**Pull request by thammegowda**
Despite these drastic changes (due to code movement), it should be backward compatible!

### CODE REVIEW

**Comment by martinpopel** [comment]
I suggest to also delete the sentence "You can also directly run the shell script sacrebleu.py in the source repository" in README.md. The original idea was to have a single-script pure-Python solution with no dependencies, but this is not true anymore (it depends on `portalocker`) and maintaining the long file is a bit uncomfortable, so I like this PR.

**Comment by thammegowda** [comment]
> I suggest to also delete the sentence "You can also directly run the shell script sacrebleu.py in the source repository" in README.md

@martinpopel  Thanks for the suggestion. I just updated the README.

> I'm going to need some time to review and check, which I hope to do by next week. Thanks for doing the work.  

@mjpost  Sure, no hurries. I was trying to modify a bit (for understanding/educational purpose), and I felt it would be nice to move all the datasets into a separate script because they take too many lines plus they keep growing more over the time.

**Comment by mjpost** [comment]
Can I ask you to rebase this on the latest `master` branch? I will then attend to it right away, so you won't have to worry about diverging again.

**Comment by thammegowda** [comment]
yes, I will resolve these conflicts today (ASAP) and make it ready to merge.

**Comment by thammegowda** [comment]
@mjpost successfully resolved merge issues with the latest `master` and all checks+tests from CI are passing. 
 
This is an unusual PR with a lot of code movements. 
Please have a look and let me know if there is anything I may have missed.

**Comment by mjpost** [comment]
Thank you! Testing now.

**Comment by mjpost** [comment]
Thank you! Will release 1.4.6 now.

**Pull request merged**
