### PR TITLE
BLEU variable references: fix for empty hypotheses

### PR DESCRIPTION
**Pull request by tuetschek**
This is a fix for a problem @ozancaglayan mentioned in #132 -- if the hypothesis is empty, we don't want it to be removed from `lines` and compare just references among themselves.

### CODE REVIEW

**Comment by ozancaglayan** [comment]
@mjpost I've added some new tests here, including the one for this specific case.

**Review by ozancaglayan — APPROVED** [review]

**Comment by mjpost** [comment]
Thanks, all! I just released [sacrebleu 1.5.0](https://pypi.org/project/sacrebleu/).

**Comment by ozancaglayan** [comment]
thanks, sorry didn't have time for the final thing. Are you planning to do a release on github as well? Because it's still showing 1.4.13 as the latest release there.

**Comment by mjpost** [comment]
No problem. It's in the Makefile, though: `make publish`.

I have never done a release manually. I thought Github did it automatically, but I see you did the last one yourself. I just went through the process manually, though. I wonder if, when I created the tag, I should have used `git tag -a` and then added the bit from the Changelog. I suspect that would have auto-created a release.

**Comment by ozancaglayan** [comment]
Thinking back on this, although this is only available through the API, the `num_refs` in the signature became quite ambiguous, no?

**Pull request merged**
