### PR TITLE
Allows calling the script as a standalone utility (#86)

### PR DESCRIPTION
**Pull request by ozancaglayan**
I tested it with installed sacrebleu, with `-m sacrebleu` from root dir, calling the script from arbitrary places (when installed and not-installed). It seems to work.

### CODE REVIEW

**Comment by martinpopel** [comment]
I tested this by uninstalling sacrebleu, then `git clone https://github.com/mjpost/sacrebleu; git pull https://github.com/ozancaglayan/sacrebleu.git fix-86` and then executed `python3 -m sacrebleu -V`.
First, it failed with `No module named 'MeCab'`, but this is expected that I need to install the dependencies first.
After installing MeCab, it works (prints `__main__.py 1.4.12`), but only from the directory with `sacrebleu.py`.
If `sacrebleu.py` is e.g. in `path/to/sacrebleu`, I need to run it as `python3 -m path.to.sacrebleu.sacrebleu -V`.

I thought the goal was to run it as `path/to/sacrebleu/sacrebleu.py -V`.
Unfortunately, this does not work for me -- it fails with
```
Traceback (most recent call last):
  File "path/to/sacrebleu/sacrebleu.py", line 38, in <module>
    from .tokenizers import TOKENIZERS, DEFAULT_TOKENIZER
SystemError: Parent module 'sacrebleu' not loaded, cannot perform relative import
```

**Comment by ozancaglayan** [comment]
Interesting, it was working for me when I sent this but I will recheck what's going on. Thanks!

**Comment by ozancaglayan** [comment]
This still works for me (with and without installing the package)

```bash
$ git clone git clone https://github.com/mjpost/sacrebleu
$ cd sacrebleu
$ gh pr checkout 95
# Is it installed?
$ which sacrebleu
# Check python path
$ python -c 'import sys; print("\n".join(sys.path))'

/home/ozan/anaconda3/lib/python37.zip
/home/ozan/anaconda3/lib/python3.7
/home/ozan/anaconda3/lib/python3.7/lib-dynload
/home/ozan/anaconda3/lib/python3.7/site-packages
/home/ozan/git/transformers

# OK, go back to home
$ cd

$ ./sacrebleu/sacrebleu/sacrebleu.py -V
sacrebleu.py 1.4.12

$ cd sacrebleu
$ python -m sacrebleu -V
# this should be fixed BTW, it should return a static string for correctness
__main__.py 1.4.12

**Comment by martinpopel** [comment]
When replicating the steps on another computer it worked, but on my notebook it still fails. Maybe there is something wrong with my python installation, but unfortunately, I am too busy to delve into it now. You can merge this and we will see if other users can use it as a standalone script or if the file a new issue.

**Comment by ozancaglayan** [comment]
Re-added this into 1.4.14 PR since it's a trivial commit. Thanks!

**Pull request closed without merging**
