### PR TITLE
fix paths for wmt18 extra test sets

### PR DESCRIPTION
**Pull request by ozancaglayan**

### CODE REVIEW

**Review by martinpopel — APPROVED** [review]

**Review by mjpost — APPROVED** [review]
LGTM.

**Comment by ozancaglayan** [comment]
Thanks. It seemed important for a 1.5.1, but it's up to you.

**Comment by mjpost** [comment]
@ozancaglayan we should do a 1.5.1 release. Do you have time to update CHANGELOG and version and create a PR? If you and @martinpopel send me your mypy account IDs, I can add you to permissions for pushing out new versions, too.

**Comment by mjpost** [comment]
We could include #136 with it as well.

**Comment by martinpopel** [comment]
> If you and @martinpopel send me your mypy account IDs

I guess you mean PyPI, not mypy. My ID is "popel". I don't have much time for sacrebleu now, but I hope it will change soon.

**Comment by ozancaglayan** [comment]
I can do it tomorrow, I had already done once so I assume you've added me
there.

**Comment by ozancaglayan** [comment]
v1.5.1 is tagged and released on github and PyPI.

**Pull request merged**
