### PR TITLE
Add a Japanese tokenizer

### PR DESCRIPTION
**Pull request by MorinoseiMorizo**
For evaluating Japanese, a Japanese word tokenizer is required.
This PR adds MeCab tokenizer that is one of the most used Japanese tokenizers.
Tested on macOS Catalina and CentOS 7.

### CODE REVIEW

**Comment by MorinoseiMorizo** [comment]
It looks like I need to fix some.
I'll try.

**Comment by MorinoseiMorizo** [comment]
Now it works.
Could you review this, please?

**Comment by Zenglinxiao** [comment]
LGTM.
By the way, do you @MorinoseiMorizo think it will be appropriate if we can evaluate Japanese translation on Character level just as Chinese as they both share the same properties (no space between word, word created based on a sequence of character, etc.) ?
As the evaluation of Japenese (in WAT) based on Kytea/Mecab/Juman varies not only on the tokenizer itself (3 tokenizer tool * different version), but also on the dictionary/model, making it complicated and unreliable.
By doing evaluation on character level, we can just add the Kana characters Unicode range on `is_chinese_char` to make an `is_CJK_char` function tackling all this kind issue.

**Comment by mjpost** [comment]
I haven't had a chance to review this, but hope to soon. Please ping again if too much time passes.

**Comment by MorinoseiMorizo** [comment]
@Zenglinxiao Thank you for the comment.
Your concern that evaluating Japanese tokenizers relies on dictionaries or models is true.
IMHO, however, it is difficult to evaluate Japanese sentence with character-level.
Because Japanese express a word with several characters, this makes it difficult to correctly evaluate with up to 4-gram character matching.
Chinese has more information per character, thus we can evaluate it with character-level.

In this PR, I verify the used dictionary is the IPA dictionary for the reliability.
https://github.com/mjpost/sacreBLEU/pull/61/files#diff-4f745f055813d88517d38580ca48abfbR913

Thanks!

**Comment by butsugiri** [comment]
@mjpost Any updates on this PR? I love sacreBLEU and would really like to use it for evaluating Japanese MT.

**Comment by mjpost** [comment]
I hope to look at this by tomorrow with #66 and #68. Thanks for the ping.

**Comment by mjpost** [comment]
Thanks for the commit! I'll release 1.4.5 next.

**Comment by davidbaines** [comment]
I get an error trying to 
pip install sacrebleu

I wonder whether it is this commit that now prevents me from installing sacrebleu on Windows?

(OpenNMT_tf) C:\Users\David>pip install sacrebleu
Collecting sacrebleu
  Using cached sacrebleu-1.4.6-py3-none-any.whl (59 kB)
Collecting mecab-python3
  Using cached mecab-python3-0.996.5.tar.gz (65 kB)
Requirement already satisfied: portalocker in c:\users\david\anaconda3\envs\opennmt_tf\lib\site-packages (from sacrebleu) (1.7.0)
Requirement already satisfied: typing in c:\users\david\anaconda3\envs\opennmt_tf\lib\site-packages (from sacrebleu) (3.7.4.1)
Requirement already satisfied: pywin32!=226; platform_system == "Windows" in c:\users\david\anaconda3\envs\opennmt_tf\lib\site-packages (from portalocker->sacrebleu) (227)
Building wheels for collected packages: mecab-python3
  Building wheel for mecab-python3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\David\AppData\Local\Temp\pip-wheel-6hv7yttu'
       cwd: C:\Users\David\AppData\Local\Temp\pip-install-7ez0vltn\mecab-python3\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\MeCab
  copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
  running build_ext
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for mecab-python3
  Running setup.py clean for mecab-python3
Failed to build mecab-python3
Installing collected packages: mecab-python3, sacrebleu
    Running setup.py install for mecab-python3 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-qbdi82e5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\Include\mecab-python3'
         cwd: C:\Users\David\AppData\Local\Temp\pip-install-7ez0vltn\mecab-python3\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\MeCab
    copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-7ez0vltn\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-qbdi82e5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\David\Anaconda3\envs\OpenNMT_tf\Include\mecab-python3' Check the logs for full command output.

**Comment by mjpost** [comment]
Hi @davidbaines, thanks for posting. Let's discuss this in #74.

**Pull request merged**
