### PR TITLE
New release (1.4.14)

### PR DESCRIPTION
**Pull request by mjpost**
This includes TER, char-based tokenization, and the WMT20 robustness datasets (#103).

@ozancaglayan, do you want to add #95 to this, too? Or should that wait?

### CODE REVIEW

**Comment by ozancaglayan** [comment]
@martinpopel said that #95 did not fix the issue for him although I double tested it. Since there are no further feedbacks about that, it can wait..

**Review by ozancaglayan — APPROVED** [review]

**Comment by ozancaglayan** [comment]
I will merge #95 as well and then test the master branch thoroughly.

**Comment by mjpost** [comment]
Hi @ozancaglayan, it looks like that build failure was a fluke. Is this ready to merge? I'd like to release 1.4.14.

**Comment by ozancaglayan** [comment]
I remember that everything was OK.

**Comment by ozancaglayan** [comment]
@mjpost I've pushed the package to testPyPI, installed and tested it with BLEU and TER.
You can install with this `pip install -i https://test.pypi.org/simple/ sacrebleu`

**Pull request merged**
